<program> ::= <top_list>

<top_list> ::= <top_decl>
             | <top_list> <top_decl>

<top_decl> ::= <manifest_decl>
             | <incant_decl>
             | <type_decl>
             | <instance_decl>
             | <attribute_apply_decl>
             | NEWLINE

<manifest_decl> ::= <module_ref> "manifests" "[" <manifest_symbol_list> "]" <stmt_end_opt>

<module_ref> ::= IDENTIFIER
               | IDENTIFIER "(" STRING ")"

<manifest_symbol_list> ::= IDENTIFIER
                         | <manifest_symbol_list> "," IDENTIFIER

<incant_decl> ::= "incant" IDENTIFIER "[" <param_list_opt> "]" <block_like>

<type_decl> ::= "type" IDENTIFIER [<metadata_prefix>] <stmt_end_opt>

<instance_decl> ::= "instance" [<metadata_prefix>] IDENTIFIER ":" IDENTIFIER <stmt_end_opt>

<metadata_prefix> ::= "^" <object_literal>
                    | "^~" <object_literal>

<param_list_opt> ::= /* empty */
                   | <param_list>

<param_list> ::= <param>
               | <param_list> "," <param>

<param> ::= IDENTIFIER ":" IDENTIFIER

<attribute_apply_decl> ::= ":" IDENTIFIER <object_literal>

<block_like> ::= <expression>
               | <object_literal>
               | NEWLINE INDENT <pipeline_seq> DEDENT

<pipeline_seq> ::= <pipeline_item>
                 | <pipeline_seq> NEWLINE <pipeline_item>

<pipeline_item> ::= <expression>

<expression> ::= <pipe_expr>

<pipe_expr> ::= <ternary_expr>
              | <pipe_expr> "|" <ternary_expr>

<ternary_expr> ::= <postfix_expr>
                 | <postfix_expr> "if" <expression> "else" <expression>

<postfix_expr> ::= <atom_expr>
                 | <postfix_expr> "." IDENTIFIER
                 | <postfix_expr> <record_call>

<record_call> ::= "{" <arg_field_list_opt> "}"

<arg_list_opt> ::= /* empty */
                 | <arg_list>

<arg_list> ::= <expression>
             | <arg_list> <expression>
             | <arg_list> "," <expression>

<arg_field_list_opt> ::= /* empty */
                       | <arg_field_list>

<arg_field_list> ::= <arg_field>
                   | <arg_field_list> <arg_field_sep> <arg_field>

<arg_field_sep> ::= ";"
                  | ","
                  | NEWLINE

<arg_field> ::= IDENTIFIER ":" <expression>
              | IDENTIFIER

<atom_expr> ::= IDENTIFIER
              | NUMBER
              | STRING
              | ":" IDENTIFIER
              | <prefix_call>
              | <lambda_literal>
              | <list_literal>
              | <object_literal>

<prefix_call> ::= "(" <callable_expr> <arg_list_opt> ")"

<callable_expr> ::= <callable_path>
                  | "+"
                  | "-"
                  | "*"
                  | "/"
                  | "%"

<callable_path> ::= IDENTIFIER
                  | <callable_path> "." IDENTIFIER

<lambda_literal> ::= "(" "[" <param_list_opt> "]" "," <expression> ")"
                   | "[" "[" <param_list_opt> "]" "," <expression> "]"

<list_literal> ::= "[" <list_items_opt> "]"

<list_items_opt> ::= /* empty */
                   | <list_items>

<list_items> ::= <list_item>
               | <list_items> "," <list_item>
               | <list_items> <list_item>

<list_item> ::= <expression>
              | IDENTIFIER "as" <expression>
              | <param>

<object_literal> ::= "{" <object_field_list_opt> "}"

<object_field_list_opt> ::= /* empty */
                          | <object_field_list>

<object_field_list> ::= <object_field>
                      | <object_field_list> <object_field_sep> <object_field>

<object_field_sep> ::= ";"
                     | ","
                     | NEWLINE

<object_field> ::= IDENTIFIER ":" <expression>
                 | IDENTIFIER

<stmt_end_opt> ::= /* empty */
                 | ";"
                 | NEWLINE
